### ISSUE TITLE
Authentication fails when using a custom user model

### ISSUE THREAD

**Issue by alandmoore** [sjkingo/django_auth_ldap3#14]
django_auth_ldap3 fails when trying to authenticate in an app that uses a custom user model (in my case, by subclassing `AbstractUser` and setting `AUTH_USER_MODEL` to the new class).

The solution (at least in django 1.8 and higher) is to use `django.contrib.auth.get_user_model()` to determine the model to use, rather than directly importing `User`.

I will make a pull request shortly with a patch.

**Comment by sjkingo** [comment]
Ohh I didn't even think of that. Thanks Alan.

I think we should look at dropping support for 1.6 and 1.7 now that 1.8 is the new LTS and <1.8 is unsupported. I'll open an issue for that. (edit: #15)
